'use client'

import { Card, CardContent } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { 
  TrendingUp,
  DollarSign,
  Users,
  Globe,
  Building2,
  Zap,
  Award,
  BarChart3
} from 'lucide-react'
import { motion } from 'framer-motion'

const stats = [
  {
    category: 'Platform Growth',
    metrics: [
      {
        icon: DollarSign,
        value: '$8.4M+',
        label: 'Monthly Partner Revenue',
        change: '+240%',
        changeType: 'positive' as const,
        description: 'Generated by our partner ecosystem in the last 30 days'
      },
      {
        icon: Users,
        value: '315+',
        label: 'Active Partners',
        change: '+180%',
        changeType: 'positive' as const,
        description: 'Resellers, SIs, and enterprise customers globally'
      },
      {
        icon: Globe,
        value: '42',
        label: 'Countries',
        change: '+85%',
        changeType: 'positive' as const,
        description: 'Global presence across all major markets'
      }
    ]
  },
  {
    category: 'Technical Excellence',
    metrics: [
      {
        icon: Zap,
        value: '99.99%',
        label: 'Platform Uptime',
        change: 'SLA',
        changeType: 'neutral' as const,
        description: 'Enterprise-grade reliability with automatic failover'
      },
      {
        icon: BarChart3,
        value: '<50ms',
        label: 'API Response Time',
        change: 'P99',
        changeType: 'neutral' as const,
        description: 'Lightning-fast performance across all endpoints'
      },
      {
        icon: Building2,
        value: '1.2M+',
        label: 'Daily Transactions',
        change: '+320%',
        changeType: 'positive' as const,
        description: 'Processed through our blockchain gateway'
      }
    ]
  },
  {
    category: 'Partner Success',
    metrics: [
      {
        icon: Award,
        value: '94%',
        label: 'Partner Satisfaction',
        change: '+12%',
        changeType: 'positive' as const,
        description: 'Based on quarterly partner success surveys'
      },
      {
        icon: TrendingUp,
        value: '$75K',
        label: 'Avg Partner MRR',
        change: '+165%',
        changeType: 'positive' as const,
        description: 'Monthly recurring revenue per active partner'
      },
      {
        icon: Users,
        value: '5.2x',
        label: 'Revenue Multiplier',
        change: '+40%',
        changeType: 'positive' as const,
        description: 'Average revenue growth after joining ecosystem'
      }
    ]
  }
]

const highlights = [
  {
    title: 'Market Leadership',
    value: '#1',
    description: 'Banking-to-blockchain integration platform by market share',
    icon: Award
  },
  {
    title: 'Developer Adoption',
    value: '25K+',
    description: 'Monthly active developers across 5 language SDKs',
    icon: Users
  },
  {
    title: 'Enterprise Customers',
    value: '120+',
    description: 'Fortune 500 companies using our self-service platform',
    icon: Building2
  },
  {
    title: 'Total Platform Volume',
    value: '$2.8B+',
    description: 'Processed through our infrastructure annually',
    icon: DollarSign
  }
]

export function Stats() {
  return (
    <section className="py-24 bg-white dark:bg-gray-900">
      <div className="mx-auto max-w-7xl px-6 lg:px-8">
        <div className="text-center mb-16">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
          >
            <Badge variant="outline" className="mb-4">
              <BarChart3 className="w-4 h-4 mr-2" />
              Platform Metrics
            </Badge>
            <h2 className="text-3xl font-bold tracking-tight text-gray-900 dark:text-white sm:text-4xl">
              Proven Success at Scale
            </h2>
            <p className="mt-4 text-lg text-gray-600 dark:text-gray-300 max-w-3xl mx-auto">
              Numbers that matter: partner revenue, platform performance, and market leadership 
              metrics that demonstrate our commitment to your success.
            </p>
          </motion.div>
        </div>

        {/* Key Highlights */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5, delay: 0.1 }}
          className="mb-16"
        >
          <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-4">
            {highlights.map((highlight, index) => {
              const Icon = highlight.icon
              return (
                <motion.div
                  key={highlight.title}
                  initial={{ opacity: 0, scale: 0.95 }}
                  whileInView={{ opacity: 1, scale: 1 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.5, delay: 0.1 + (index * 0.05) }}
                >
                  <Card className="border-2 border-dashed border-gray-300 dark:border-gray-600 hover:border-blue-500 dark:hover:border-blue-400 transition-colors">
                    <CardContent className="p-6 text-center">
                      <div className="flex justify-center mb-4">
                        <div className="flex h-12 w-12 items-center justify-center rounded-full bg-blue-100 dark:bg-blue-900">
                          <Icon className="h-6 w-6 text-blue-600 dark:text-blue-400" />
                        </div>
                      </div>
                      <div className="text-3xl font-bold text-gray-900 dark:text-white mb-2">
                        {highlight.value}
                      </div>
                      <div className="text-sm font-medium text-gray-900 dark:text-white mb-1">
                        {highlight.title}
                      </div>
                      <div className="text-xs text-gray-500 dark:text-gray-400">
                        {highlight.description}
                      </div>
                    </CardContent>
                  </Card>
                </motion.div>
              )
            })}
          </div>
        </motion.div>

        {/* Detailed Stats by Category */}
        <div className="space-y-12">
          {stats.map((category, categoryIndex) => (
            <motion.div
              key={category.category}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: categoryIndex * 0.1 }}
            >
              <h3 className="text-2xl font-semibold text-gray-900 dark:text-white text-center mb-8">
                {category.category}
              </h3>
              
              <div className="grid grid-cols-1 gap-6 lg:grid-cols-3">
                {category.metrics.map((metric, index) => {
                  const Icon = metric.icon
                  return (
                    <motion.div
                      key={metric.label}
                      initial={{ opacity: 0, y: 20 }}
                      whileInView={{ opacity: 1, y: 0 }}
                      viewport={{ once: true }}
                      transition={{ duration: 0.5, delay: (categoryIndex * 0.1) + (index * 0.05) }}
                    >
                      <Card className="h-full hover:shadow-lg transition-shadow duration-300">
                        <CardContent className="p-6">
                          <div className="flex items-start justify-between mb-4">
                            <div className="flex h-12 w-12 items-center justify-center rounded-lg bg-gradient-to-br from-blue-500 to-indigo-600">
                              <Icon className="h-6 w-6 text-white" />
                            </div>
                            <Badge 
                              variant={metric.changeType === 'positive' ? 'default' : 'secondary'}
                              className={
                                metric.changeType === 'positive' 
                                  ? 'bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-300' 
                                  : ''
                              }
                            >
                              {metric.change}
                            </Badge>
                          </div>
                          
                          <div className="space-y-2">
                            <div className="text-3xl font-bold text-gray-900 dark:text-white">
                              {metric.value}
                            </div>
                            <div className="text-lg font-medium text-gray-700 dark:text-gray-300">
                              {metric.label}
                            </div>
                            <p className="text-sm text-gray-500 dark:text-gray-400 leading-relaxed">
                              {metric.description}
                            </p>
                          </div>
                        </CardContent>
                      </Card>
                    </motion.div>
                  )
                })}
              </div>
            </motion.div>
          ))}
        </div>

        {/* Revenue Growth Chart Section */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5, delay: 0.4 }}
          className="mt-16"
        >
          <Card className="bg-gradient-to-br from-blue-50 to-indigo-50 dark:from-blue-950 dark:to-indigo-950 border-blue-200 dark:border-blue-800">
            <CardContent className="p-8">
              <div className="text-center mb-8">
                <h3 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">
                  Partner Revenue Growth Trajectory
                </h3>
                <p className="text-gray-600 dark:text-gray-300">
                  Proven 240% year-over-year growth across all partner channels
                </p>
              </div>
              
              <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
                <div className="text-center">
                  <div className="text-2xl font-bold text-blue-600 dark:text-blue-400 mb-1">Q1 2024</div>
                  <div className="text-sm text-gray-500 dark:text-gray-400 mb-2">$2.1M MRR</div>
                  <div className="w-full bg-gray-200 dark:bg-gray-700 rounded-full h-2">
                    <div className="bg-blue-600 h-2 rounded-full" style={{ width: '25%' }}></div>
                  </div>
                </div>
                <div className="text-center">
                  <div className="text-2xl font-bold text-blue-600 dark:text-blue-400 mb-1">Q2 2024</div>
                  <div className="text-sm text-gray-500 dark:text-gray-400 mb-2">$4.2M MRR</div>
                  <div className="w-full bg-gray-200 dark:bg-gray-700 rounded-full h-2">
                    <div className="bg-blue-600 h-2 rounded-full" style={{ width: '50%' }}></div>
                  </div>
                </div>
                <div className="text-center">
                  <div className="text-2xl font-bold text-blue-600 dark:text-blue-400 mb-1">Q3 2024</div>
                  <div className="text-sm text-gray-500 dark:text-gray-400 mb-2">$6.8M MRR</div>
                  <div className="w-full bg-gray-200 dark:bg-gray-700 rounded-full h-2">
                    <div className="bg-blue-600 h-2 rounded-full" style={{ width: '80%' }}></div>
                  </div>
                </div>
                <div className="text-center">
                  <div className="text-2xl font-bold text-green-600 dark:text-green-400 mb-1">Q4 2024</div>
                  <div className="text-sm text-gray-500 dark:text-gray-400 mb-2">$8.4M MRR</div>
                  <div className="w-full bg-gray-200 dark:bg-gray-700 rounded-full h-2">
                    <div className="bg-green-600 h-2 rounded-full" style={{ width: '100%' }}></div>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </motion.div>
      </div>
    </section>
  )
}